window.__ModuleLoader__.load({
  id: "@local/dsh-3d-model-viewer",
  factory: (require) => {
    const module = { exports: {} };
    const exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    const React = require("react");
    const h = React.createElement;

    const CSS = `
[data-dsh-3d-trigger]{box-sizing:border-box;color:var(--dsw-alias-label-primary);background:transparent;border:0;cursor:pointer;font:inherit}
.d3v-trigger{width:100%;height:42px;border-radius:12px;display:flex;align-items:center;gap:9px;padding:0 10px;margin-top:4px}
.d3v-trigger:hover{background:var(--dsw-alias-interactive-bg-hover)}.d3v-trigger.rail{width:36px;height:36px;padding:0;justify-content:center;border-radius:50%}.d3v-icon{font-size:19px;line-height:1}.d3v-label{font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.d3v-backdrop{position:fixed;inset:0;z-index:1000;background:rgba(5,10,20,.62);backdrop-filter:blur(3px);display:flex;align-items:center;justify-content:center;padding:20px}
.d3v-dialog{width:min(1080px,calc(100vw - 40px));height:min(780px,calc(100vh - 40px));background:var(--dsw-specific-menu,#17191d);color:var(--dsw-alias-label-primary,#eee);border:1px solid var(--dsw-alias-border-l1,#444);border-radius:16px;box-shadow:0 22px 80px rgba(0,0,0,.45);display:grid;grid-template-rows:auto 1fr auto;overflow:hidden}
.d3v-header{height:56px;display:flex;align-items:center;gap:12px;padding:0 16px;border-bottom:1px solid var(--dsw-alias-border-l1,#333)}.d3v-title{font-size:16px;font-weight:600}.d3v-sub{color:var(--dsw-alias-label-tertiary,#999);font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.d3v-spacer{flex:1}
.d3v-btn{appearance:none;border:1px solid var(--dsw-alias-border-l2,#555);background:var(--dsw-alias-interactive-bg-hover,#292c31);color:inherit;border-radius:8px;padding:7px 11px;cursor:pointer;font:inherit;font-size:13px}.d3v-btn:hover{filter:brightness(1.12)}.d3v-close{font-size:20px;padding:3px 9px}
.d3v-stage{position:relative;min-height:0;background:radial-gradient(circle at 50% 35%,#303845 0,#171b22 55%,#101217 100%)}.d3v-canvas{width:100%;height:100%;display:block;touch-action:none;cursor:grab}.d3v-canvas:active{cursor:grabbing}.d3v-empty{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;pointer-events:none}.d3v-empty-card{text-align:center;color:#c8d0dc}.d3v-empty-icon{font-size:52px;opacity:.7;margin-bottom:14px}.d3v-empty-note{font-size:13px;color:#8993a3;margin-top:7px}.d3v-drop{outline:2px dashed #60a5fa;outline-offset:-10px}
.d3v-error{position:absolute;left:14px;right:14px;top:14px;padding:10px 12px;border-radius:9px;background:#591d25;color:#ffd6da;font-size:13px}.d3v-help{position:absolute;right:13px;bottom:11px;color:#9da8b8;background:rgba(10,12,17,.65);border-radius:7px;padding:5px 8px;font-size:11px;pointer-events:none}
.d3v-footer{min-height:44px;display:flex;align-items:center;gap:18px;padding:0 16px;border-top:1px solid var(--dsw-alias-border-l1,#333);font-size:12px;color:var(--dsw-alias-label-secondary,#bbb);flex-wrap:wrap}.d3v-stat b{color:var(--dsw-alias-label-primary,#eee);font-weight:500}.d3v-input{display:none}
.d3v-session-btn{appearance:none;border:1px solid var(--dsw-alias-border-l2,#555);background:var(--dsw-alias-interactive-bg-hover,#292c31);color:var(--dsw-alias-label-primary,#eee);border-radius:8px;padding:5px 10px;cursor:pointer;font:inherit;font-size:12px}.d3v-session-btn:hover{filter:brightness(1.12)}
.d3v-drawer-wrap{position:fixed;inset:0;z-index:900;pointer-events:none}.d3v-drawer-backdrop{position:absolute;inset:0;background:rgba(5,10,20,.18);pointer-events:auto}.d3v-drawer{position:absolute;right:0;top:0;bottom:0;width:min(880px,72vw);min-width:560px;background:var(--dsw-specific-menu,#17191d);color:var(--dsw-alias-label-primary,#eee);border-left:1px solid var(--dsw-alias-border-l1,#444);box-shadow:-18px 0 55px rgba(0,0,0,.28);pointer-events:auto;display:grid;grid-template-rows:auto 1fr;overflow:hidden}.d3v-drawer-head{height:54px;display:flex;align-items:center;gap:10px;padding:0 13px;border-bottom:1px solid var(--dsw-alias-border-l1,#333)}.d3v-drawer-body{min-height:0;display:grid;grid-template-columns:240px minmax(0,1fr)}.d3v-browser{min-width:0;border-right:1px solid var(--dsw-alias-border-l1,#333);display:grid;grid-template-rows:auto 1fr auto;background:rgba(10,12,17,.16)}.d3v-search-wrap{padding:10px}.d3v-search{box-sizing:border-box;width:100%;height:34px;border:1px solid var(--dsw-alias-border-l2,#555);border-radius:8px;background:var(--dsw-alias-interactive-bg-hover,#292c31);color:inherit;font:inherit;padding:0 10px;outline:none}.d3v-search:focus{border-color:#60a5fa}.d3v-files{min-height:0;overflow-y:auto;padding:0 7px 8px;display:flex;flex-direction:column;gap:3px}.d3v-file{appearance:none;width:100%;border:0;border-radius:8px;background:transparent;color:inherit;text-align:left;padding:8px;cursor:pointer;display:grid;grid-template-columns:32px minmax(0,1fr);gap:8px}.d3v-file:hover{background:var(--dsw-alias-interactive-bg-hover,#292c31)}.d3v-file.active{background:rgba(59,130,246,.16);box-shadow:inset 2px 0 #60a5fa}.d3v-file-icon{width:32px;height:32px;border-radius:7px;background:rgba(96,165,250,.13);color:#93c5fd;display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:700}.d3v-file-main{min-width:0}.d3v-file-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;line-height:17px}.d3v-file-meta{color:var(--dsw-alias-label-tertiary,#8993a3);font-size:10px;line-height:15px;display:flex;gap:7px}.d3v-browser-foot{border-top:1px solid var(--dsw-alias-border-l1,#333);padding:8px 10px;color:var(--dsw-alias-label-tertiary,#8993a3);font-size:11px}.d3v-preview-column{min-width:0;min-height:0;display:grid;grid-template-rows:1fr auto}.d3v-live{display:inline-flex;align-items:center;gap:5px;font-size:11px;color:#86efac}.d3v-live:before{content:'';width:6px;height:6px;border-radius:50%;background:#22c55e}.d3v-loading{position:absolute;left:12px;top:12px;color:#cbd5e1;background:rgba(10,12,17,.7);padding:6px 9px;border-radius:7px;font-size:12px}
@media(max-width:760px){.d3v-drawer{width:100vw;min-width:0}.d3v-drawer-body{grid-template-columns:150px minmax(0,1fr)}}
`;
    if (!document.querySelector('style[data-plugin-css="dsh-3d-model-viewer"]')) {
      const s = document.createElement("style"); s.dataset.pluginCss = "dsh-3d-model-viewer"; s.textContent = CSS; document.head.appendChild(s);
    }

    function makeStore() {
      let state = { open:false, name:"", mesh:null, error:"", loading:false };
      const listeners = new Set();
      return { getSnapshot:()=>state, subscribe:(fn)=>(listeners.add(fn),()=>listeners.delete(fn)), set:(patch)=>{state={...state,...patch};listeners.forEach(fn=>fn());} };
    }
    function makeSessionStore(){let state={files:[],selected:"",mesh:null,error:"",loading:false,mtime:0};const listeners=new Set();return{getSnapshot:()=>state,subscribe:fn=>(listeners.add(fn),()=>listeners.delete(fn)),set:patch=>{state={...state,...patch};listeners.forEach(fn=>fn());}};}
    const useStore = (store) => React.useSyncExternalStore(store.subscribe, store.getSnapshot, store.getSnapshot);

    function Trigger({ wide, store }) {
      return h("button", { type:"button", className:"d3v-trigger"+(wide?"":" rail"), "data-dsh-3d-trigger":"", title:"3D 模型预览", onClick:()=>store.set({open:true}) },
        h("span",{className:"d3v-icon","aria-hidden":"true"},"◇"), wide&&h("span",{className:"d3v-label"},"3D 模型预览"));
    }

    function parseBinaryStl(buf) {
      const dv=new DataView(buf); if(buf.byteLength<84) throw Error("STL 文件过短");
      const n=dv.getUint32(80,true); if(n>5000000) throw Error("模型超过 500 万三角面限制");
      if(84+n*50>buf.byteLength) throw Error("STL 三角面数据不完整");
      const out=new Float32Array(n*18); let p=0;
      for(let i=0,o=84;i<n;i++,o+=50){let nx=dv.getFloat32(o,true),ny=dv.getFloat32(o+4,true),nz=dv.getFloat32(o+8,true);const ax=dv.getFloat32(o+12,true),ay=dv.getFloat32(o+16,true),az=dv.getFloat32(o+20,true),bx=dv.getFloat32(o+24,true),by=dv.getFloat32(o+28,true),bz=dv.getFloat32(o+32,true),cx=dv.getFloat32(o+36,true),cy=dv.getFloat32(o+40,true),cz=dv.getFloat32(o+44,true);if(!Number.isFinite(nx+ny+nz)||Math.hypot(nx,ny,nz)<1e-8){const ux=bx-ax,uy=by-ay,uz=bz-az,vx=cx-ax,vy=cy-ay,vz=cz-az;nx=uy*vz-uz*vy;ny=uz*vx-ux*vz;nz=ux*vy-uy*vx;}const l=Math.hypot(nx,ny,nz)||1;nx/=l;ny/=l;nz/=l;for(const v of [[ax,ay,az],[bx,by,bz],[cx,cy,cz]]){out[p++]=v[0];out[p++]=v[1];out[p++]=v[2];out[p++]=nx;out[p++]=ny;out[p++]=nz;}}
      return finishMesh(out,n);
    }
    function parseAsciiStl(buf){const text=new TextDecoder().decode(buf);const re=/facet\s+normal\s+([-+\deE.]+)\s+([-+\deE.]+)\s+([-+\deE.]+)[\s\S]*?outer\s+loop([\s\S]*?)endloop/gi;const a=[];let m;while((m=re.exec(text))){const n=[+m[1],+m[2],+m[3]], verts=[...m[4].matchAll(/vertex\s+([-+\deE.]+)\s+([-+\deE.]+)\s+([-+\deE.]+)/gi)].slice(0,3);if(verts.length===3)for(const v of verts)a.push(+v[1],+v[2],+v[3],...n);}if(!a.length)throw Error("无法识别 ASCII STL");return finishMesh(new Float32Array(a),a.length/18);}
    function parseStl(buf){if(buf.byteLength>=84){const n=new DataView(buf).getUint32(80,true);if(84+n*50<=buf.byteLength)return parseBinaryStl(buf);}return parseAsciiStl(buf);}

    async function unzip(buf){const u=new Uint8Array(buf),dv=new DataView(buf),u64=o=>Number(dv.getBigUint64(o,true));let e=-1;for(let i=u.length-22;i>=Math.max(0,u.length-65557);i--)if(dv.getUint32(i,true)===0x06054b50){e=i;break;}if(e<0)throw Error("3MF ZIP 目录缺失");let count=dv.getUint16(e+10,true),cd=dv.getUint32(e+16,true);if(cd===0xffffffff||count===0xffff){const loc=e-20;if(loc<0||dv.getUint32(loc,true)!==0x07064b50)throw Error("3MF ZIP64 定位器缺失");const z=u64(loc+8);if(dv.getUint32(z,true)!==0x06064b50)throw Error("3MF ZIP64 目录损坏");count=u64(z+32);cd=u64(z+48);}const files=[];let p=cd;for(let i=0;i<count;i++){if(dv.getUint32(p,true)!==0x02014b50)throw Error("3MF ZIP 目录损坏");const method=dv.getUint16(p+10,true),rawSize=dv.getUint32(p+20,true),unSize=dv.getUint32(p+24,true),nl=dv.getUint16(p+28,true),xl=dv.getUint16(p+30,true),cl=dv.getUint16(p+32,true),rawLo=dv.getUint32(p+42,true),name=new TextDecoder().decode(u.slice(p+46,p+46+nl));let size=rawSize,lo=rawLo,ep=p+46+nl,end=ep+xl;while(ep+4<=end){const tag=dv.getUint16(ep,true),len=dv.getUint16(ep+2,true),q=ep+4;if(tag===1){let k=q;if(unSize===0xffffffff)k+=8;if(rawSize===0xffffffff){size=u64(k);k+=8;}if(rawLo===0xffffffff)lo=u64(k);}ep=q+len;}const lnl=dv.getUint16(lo+26,true),lxl=dv.getUint16(lo+28,true),start=lo+30+lnl+lxl,raw=u.slice(start,start+size);let data;if(method===0)data=raw;else if(method===8){if(typeof DecompressionStream==="undefined")throw Error("浏览器不支持 3MF 解压");const stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream("deflate-raw"));data=new Uint8Array(await new Response(stream).arrayBuffer());}else throw Error("不支持的 ZIP 压缩方式 "+method);files.push({name,data});p+=46+nl+xl+cl;}return files;}
    async function parse3mf(buf){const files=await unzip(buf);const models=files.filter(f=>/\.model$/i.test(f.name));if(!models.length)throw Error("3MF 中没有 .model 网格");const vals=[];let triangles=0;for(const f of models){const doc=new DOMParser().parseFromString(new TextDecoder().decode(f.data),"application/xml");if(doc.querySelector("parsererror"))continue;const factor=({micron:.001,millimeter:1,centimeter:10,inch:25.4,foot:304.8,meter:1000}[doc.documentElement.getAttribute("unit")]||1);for(const mesh of doc.getElementsByTagNameNS("*","mesh")){const verts=[...mesh.getElementsByTagNameNS("*","vertex")].map(v=>[+v.getAttribute("x")*factor,+v.getAttribute("y")*factor,+v.getAttribute("z")*factor]);for(const t of mesh.getElementsByTagNameNS("*","triangle")){const ids=[+t.getAttribute("v1"),+t.getAttribute("v2"),+t.getAttribute("v3")],a=verts[ids[0]],b=verts[ids[1]],c=verts[ids[2]];if(!a||!b||!c)continue;const ux=b[0]-a[0],uy=b[1]-a[1],uz=b[2]-a[2],vx=c[0]-a[0],vy=c[1]-a[1],vz=c[2]-a[2],nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,l=Math.hypot(nx,ny,nz)||1;for(const v of [a,b,c])vals.push(v[0],v[1],v[2],nx/l,ny/l,nz/l);triangles++;if(triangles>5000000)throw Error("模型超过 500 万三角面限制");}}}if(!triangles)throw Error("3MF 中没有可显示的三角网格");return finishMesh(new Float32Array(vals),triangles);}
    function finishMesh(data,triangles){let lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(let i=0;i<data.length;i+=6)for(let j=0;j<3;j++){lo[j]=Math.min(lo[j],data[i+j]);hi[j]=Math.max(hi[j],data[i+j]);}if(!Number.isFinite(lo[0]))throw Error("模型坐标无效");const center=lo.map((x,i)=>(x+hi[i])/2),size=lo.map((x,i)=>hi[i]-x),radius=Math.hypot(...size)/2||1;return{data,triangles,lo,hi,size,center,radius};}

    const VS=`attribute vec3 p;attribute vec3 n;uniform mat4 mvp;uniform mat4 model;varying vec3 vn;void main(){gl_Position=mvp*vec4(p,1.);vn=mat3(model)*n;}`;
    const FS=`precision mediump float;varying vec3 vn;void main(){vec3 N=normalize(vn);vec3 L=normalize(vec3(.5,.8,1.));float d=max(dot(N,L),0.);float rim=pow(1.-abs(N.z),2.);vec3 c=vec3(.18,.62,.95)*(.28+.72*d)+rim*vec3(.08,.18,.28);gl_FragColor=vec4(c,1.);}`;
    function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||"着色器编译失败");return s;}
    const mul=(a,b)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;};
    const rx=a=>new Float32Array([1,0,0,0,0,Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1]);const ry=a=>new Float32Array([Math.cos(a),0,-Math.sin(a),0,0,1,0,0,Math.sin(a),0,Math.cos(a),0,0,0,0,1]);
    function Viewer({mesh,resetToken}){const ref=React.useRef(null);React.useEffect(()=>{const canvas=ref.current;if(!canvas||!mesh)return;const gl=canvas.getContext("webgl",{antialias:true,alpha:true});if(!gl)return;let program,buff,raf=0,down=false,lx=0,ly=0,yaw=.65,pitch=-.45,zoom=2.8;try{program=gl.createProgram();gl.attachShader(program,shader(gl,gl.VERTEX_SHADER,VS));gl.attachShader(program,shader(gl,gl.FRAGMENT_SHADER,FS));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)||"着色器链接失败");buff=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buff);gl.bufferData(gl.ARRAY_BUFFER,mesh.data,gl.STATIC_DRAW);const ps=gl.getAttribLocation(program,"p"),ns=gl.getAttribLocation(program,"n");gl.enableVertexAttribArray(ps);gl.vertexAttribPointer(ps,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(ns);gl.vertexAttribPointer(ns,3,gl.FLOAT,false,24,12);}catch(e){console.error(e);return;}
      const draw=()=>{raf=0;const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(canvas.clientWidth*d)),hh=Math.max(1,Math.round(canvas.clientHeight*d));if(canvas.width!==w||canvas.height!==hh){canvas.width=w;canvas.height=hh;}gl.viewport(0,0,w,hh);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const aspect=w/hh,f=1/Math.tan(Math.PI/8),near=.01,far=100;const proj=new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);const scale=1/mesh.radius,model=mul(ry(yaw),rx(pitch));model[0]*=scale;model[1]*=scale;model[2]*=scale;model[4]*=scale;model[5]*=scale;model[6]*=scale;model[8]*=scale;model[9]*=scale;model[10]*=scale;model[12]=-(model[0]*mesh.center[0]+model[4]*mesh.center[1]+model[8]*mesh.center[2]);model[13]=-(model[1]*mesh.center[0]+model[5]*mesh.center[1]+model[9]*mesh.center[2]);model[14]=-(model[2]*mesh.center[0]+model[6]*mesh.center[1]+model[10]*mesh.center[2])-zoom;gl.useProgram(program);gl.uniformMatrix4fv(gl.getUniformLocation(program,"model"),false,model);gl.uniformMatrix4fv(gl.getUniformLocation(program,"mvp"),false,mul(proj,model));gl.drawArrays(gl.TRIANGLES,0,mesh.data.length/6);};const request=()=>{if(!raf)raf=requestAnimationFrame(draw);};
      const pd=e=>{down=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId);};const pm=e=>{if(!down)return;yaw+=(e.clientX-lx)*.01;pitch=Math.max(-1.5,Math.min(1.5,pitch+(e.clientY-ly)*.01));lx=e.clientX;ly=e.clientY;request();};const pu=()=>{down=false;};const wh=e=>{e.preventDefault();zoom=Math.max(1.2,Math.min(8,zoom*Math.exp(e.deltaY*.001)));request();};canvas.addEventListener("pointerdown",pd);canvas.addEventListener("pointermove",pm);canvas.addEventListener("pointerup",pu);canvas.addEventListener("pointercancel",pu);canvas.addEventListener("wheel",wh,{passive:false});const ro=new ResizeObserver(request);ro.observe(canvas);request();return()=>{cancelAnimationFrame(raf);ro.disconnect();canvas.removeEventListener("pointerdown",pd);canvas.removeEventListener("pointermove",pm);canvas.removeEventListener("pointerup",pu);canvas.removeEventListener("pointercancel",pu);canvas.removeEventListener("wheel",wh);if(buff)gl.deleteBuffer(buff);if(program)gl.deleteProgram(program);};},[mesh,resetToken]);return h("canvas",{ref,className:"d3v-canvas","data-dsh-3d-canvas":""});}

    function Overlay({store}){const s=useStore(store),input=React.useRef(null),[drag,setDrag]=React.useState(false),[reset,setReset]=React.useState(0);React.useEffect(()=>{if(!s.open)return;const key=e=>{if(e.key==="Escape")store.set({open:false});};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key);},[s.open]);if(!s.open)return null;const load=async file=>{if(!file)return;if(file.size>250*1024*1024){store.set({error:"文件超过 250 MB 限制"});return;}store.set({loading:true,error:"",name:file.name});try{const buf=await file.arrayBuffer(),ext=file.name.toLowerCase();const mesh=ext.endsWith(".3mf")?await parse3mf(buf):parseStl(buf);store.set({mesh,loading:false});setReset(x=>x+1);}catch(e){store.set({error:e instanceof Error?e.message:String(e),loading:false,mesh:null});}};const drop=e=>{e.preventDefault();setDrag(false);load(e.dataTransfer.files[0]);};return h("div",{className:"d3v-backdrop",onMouseDown:e=>{if(e.target===e.currentTarget)store.set({open:false});}},h("section",{className:"d3v-dialog",role:"dialog","aria-modal":"true","aria-label":"3D 模型预览"},
      h("header",{className:"d3v-header"},h("div",null,h("div",{className:"d3v-title"},"3D 模型预览"),h("div",{className:"d3v-sub",title:s.name},s.name||"STL / 3MF · 文件仅在浏览器本地解析")),h("div",{className:"d3v-spacer"}),s.mesh&&h("button",{className:"d3v-btn",onClick:()=>setReset(x=>x+1)},"重置视角"),h("button",{className:"d3v-btn",onClick:()=>input.current?.click()},s.loading?"读取中…":"打开文件"),h("input",{ref:input,className:"d3v-input",type:"file",accept:".stl,.3mf,model/stl,model/3mf",onChange:e=>load(e.target.files[0])}),h("button",{className:"d3v-btn d3v-close","aria-label":"关闭",onClick:()=>store.set({open:false})},"×")),
      h("main",{className:"d3v-stage"+(drag?" d3v-drop":""),onDragOver:e=>{e.preventDefault();setDrag(true);},onDragLeave:()=>setDrag(false),onDrop:drop},s.mesh&&h(Viewer,{mesh:s.mesh,resetToken:reset}),!s.mesh&&!s.error&&h("div",{className:"d3v-empty"},h("div",{className:"d3v-empty-card"},h("div",{className:"d3v-empty-icon"},"◇"),h("div",null,s.loading?"正在解析模型…":"将 STL / 3MF 拖到这里"),h("div",{className:"d3v-empty-note"},"或点击右上角“打开文件”"))),s.error&&h("div",{className:"d3v-error"},s.error),s.mesh&&h("div",{className:"d3v-help"},"拖动旋转 · 滚轮缩放")),
      h("footer",{className:"d3v-footer"},s.mesh?h(React.Fragment,null,h("span",{className:"d3v-stat"},"三角面：",h("b",null,s.mesh.triangles.toLocaleString())),h("span",{className:"d3v-stat"},"尺寸：",h("b",null,s.mesh.size.map(v=>v.toFixed(2)).join(" × ")+" mm")),h("span",{className:"d3v-stat"},"顶点：",h("b",null,(s.mesh.data.length/6).toLocaleString()))):h("span",null,"支持二进制/ASCII STL，以及包含网格的 3MF"))));}

    async function readWorkspaceModel(path){const r=await fetch(`/3d-model-viewer/files?path=${encodeURIComponent(path)}`,{cache:"no-store"});if(!r.ok)throw Error(`读取模型失败（HTTP ${r.status}）`);const buf=await r.arrayBuffer();return path.toLowerCase().endsWith(".3mf")?parse3mf(buf):parseStl(buf);}
    function SessionAction({sessionStore,openView}){const s=useStore(sessionStore);if(!s.files.length)return null;return h("button",{type:"button",className:"d3v-session-btn","data-dsh-3d-session-trigger":"",title:`预览 ${s.files.length} 个 3D 模型`,onClick:()=>openView("3d-preview",s.selected||s.files[0].path)},`◇ 3D 预览 (${s.files.length})`);}
    function fileSize(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`;}
    function SessionDrawer({sessionStore,viewRequest,completeViewRequest}){const s=useStore(sessionStore),[reset,setReset]=React.useState(0),[query,setQuery]=React.useState("");const selected=s.files.find(x=>x.path===s.selected)||s.files[0],shown=s.files.filter(f=>f.path.toLowerCase().includes(query.trim().toLowerCase()));const load=React.useCallback(async path=>{if(!path)return;sessionStore.set({selected:path,loading:true,error:""});try{const mesh=await readWorkspaceModel(path);const row=sessionStore.getSnapshot().files.find(x=>x.path===path);sessionStore.set({mesh,loading:false,mtime:row?.mtime||0});setReset(x=>x+1);}catch(e){sessionStore.set({mesh:null,loading:false,error:e instanceof Error?e.message:String(e)});}},[sessionStore]);React.useEffect(()=>{if(viewRequest?.view!=="3d-preview")return;if(viewRequest.focus)load(viewRequest.focus);completeViewRequest();},[viewRequest]);React.useEffect(()=>{if(selected&&!s.mesh&&!s.loading)load(selected.path);},[selected?.path]);React.useEffect(()=>{if(!selected)return;const timer=setInterval(async()=>{try{const j=await fetch('/3d-model-viewer/files',{cache:'no-store'}).then(r=>r.json()),row=j.files.find(x=>x.path===selected.path);if(row&&row.mtime!==sessionStore.getSnapshot().mtime){sessionStore.set({files:j.files});load(row.path);}}catch{}},1500);return()=>clearInterval(timer);},[selected?.path,load]);return h("div",{className:"d3v-drawer-body","data-dsh-3d-drawer":""},h("aside",{className:"d3v-browser"},h("div",{className:"d3v-search-wrap"},h("input",{className:"d3v-search",type:"search",placeholder:"搜索 3D 文件…",value:query,onChange:e=>setQuery(e.target.value)})),h("div",{className:"d3v-files"},shown.map(f=>h("button",{key:f.path,className:"d3v-file"+(f.path===selected?.path?" active":""),title:f.path,onClick:()=>load(f.path)},h("span",{className:"d3v-file-icon"},f.name.toLowerCase().endsWith('.3mf')?'3MF':'STL'),h("span",{className:"d3v-file-main"},h("span",{className:"d3v-file-name"},f.name),h("span",{className:"d3v-file-meta"},h("span",null,fileSize(f.size)),h("span",null,new Date(f.mtime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})))))),!shown.length&&h("div",{className:"d3v-empty-note",style:{padding:"12px"}},"没有匹配文件")),h("div",{className:"d3v-browser-foot"},`${shown.length} / ${s.files.length} 个模型`)),h("section",{className:"d3v-preview-column"},h("div",{className:"d3v-stage"},s.mesh&&h(Viewer,{mesh:s.mesh,resetToken:reset}),s.loading&&h("div",{className:"d3v-loading"},"正在更新模型…"),s.error&&h("div",{className:"d3v-error"},s.error),s.mesh&&h("div",{className:"d3v-help"},"拖动旋转 · 滚轮缩放 · 文件变化时自动更新")),h("footer",{className:"d3v-footer"},s.mesh?h(React.Fragment,null,h("span",{className:"d3v-live"},"实时"),h("span",{className:"d3v-stat"},"三角面：",h("b",null,s.mesh.triangles.toLocaleString())),h("span",{className:"d3v-stat"},"尺寸：",h("b",null,s.mesh.size.map(v=>v.toFixed(2)).join(" × ")+" mm")),h("button",{className:"d3v-btn",onClick:()=>setReset(x=>x+1)},"重置视角")):h("span",null,"暂无可预览模型"))));}
    function SessionDrawerOverlay({sessionStore,layoutStore}){const s=useStore(layoutStore);if(!s.open)return null;return h("div",{className:"d3v-drawer-wrap"},h("div",{className:"d3v-drawer-backdrop",onClick:()=>layoutStore.set({open:false})}),h("aside",{className:"d3v-drawer",role:"complementary","aria-label":"3D 实时预览"},h("header",{className:"d3v-drawer-head"},h("div",{className:"d3v-title"},"3D 实时预览"),h("div",{className:"d3v-spacer"}),h("button",{className:"d3v-btn d3v-close",onClick:()=>layoutStore.set({open:false})},"×")),h(SessionDrawer,{sessionStore,viewRequest:null,completeViewRequest:()=>{}})));}
    function PreviewView(props){const {sessionStore,layoutStore}=props;React.useEffect(()=>{layoutStore.set({open:true});return()=>layoutStore.set({open:false});},[]);return h("div",{style:{padding:"24px",color:"var(--dsw-alias-label-secondary)"}},"3D 模型已在右侧实时预览。你可以继续在当前会话中工作。");}
    function SessionBridge({sessionStore,layoutStore,openView}){const s=useStore(sessionStore);React.useEffect(()=>{let live=true,timer;const refresh=async()=>{try{const j=await fetch('/3d-model-viewer/files',{cache:'no-store'}).then(r=>r.json());if(!live)return;const current=sessionStore.getSnapshot();sessionStore.set({files:j.files,selected:j.files.some(x=>x.path===current.selected)?current.selected:(j.files[0]?.path||"")});}catch{};timer=setTimeout(refresh,1500);};refresh();return()=>{live=false;clearTimeout(timer);};},[]);if(!s.files.length)return null;return h(SessionAction,{sessionStore,openView:(view,focus)=>{layoutStore.set({open:true});if(focus&&focus!==sessionStore.getSnapshot().selected)sessionStore.set({selected:focus,mesh:null});}});}

    const inject=["slots"];
    function apply(ctx){const store=makeStore(),sessionStore=makeSessionStore(),layoutStore=makeStore();ctx.slots.inject("conversation.session.header.actions",()=>ctx.slots.register({name:"conversation.session.header.actions",id:"3d-model-preview-action",order:70,inject:owner=>({sessionStore,layoutStore,openView:owner?.openView})},SessionBridge));ctx.slots.inject("shell.overlay",()=>ctx.slots.register({name:"shell.overlay",id:"3d-session-preview-drawer",order:70,inject:()=>({sessionStore,layoutStore})},SessionDrawerOverlay));ctx.slots.inject("sidebar.footer.action",()=>ctx.slots.register({name:"sidebar.footer.action",id:"3d-model-viewer-trigger",order:80,inject:()=>({store})},Trigger));ctx.slots.inject("shell.overlay",()=>ctx.slots.register({name:"shell.overlay",id:"3d-model-viewer-overlay",order:80,inject:()=>({store})},Overlay));}
    exports.inject=inject;exports.apply=apply;return module.exports;
  }
});
